// Auto-generated by LibreLane
module chip_top(
`ifdef USE_POWER_PINS
  inout VSS,
  inout VDD,
`endif
  inout clk_PAD,
  inout rst_n_PAD,
  inout[11:0] input_PAD,
  inout[39:0] bidir_PAD,
  inout[1:0] analog_PAD
);
endmodule
