meta:
  version: 3
  flow: Classic
  substituting_steps:

    # Disable KLayout DRC
    #KLayout.DRC: null
    #Checker.KLayoutDRC: null

    # Disable KLayout antenna check
    #KLayout.Antenna: null
    #Checker.KLayoutAntenna: null

    # Disable KLayout density check
    #KLayout.Density: null
    #Checker.KLayoutDensity: null

    # Save time during development
    # Enable for sign-off
    #OpenROAD.IRDropReport: null
    #Magic.DRC: null
    #Checker.MagicDRC: null
    #KLayout.XOR: null
    #Netgen.LVS: null
    #Checker.LVS: null

DESIGN_NAME: A58_ACE
VERILOG_FILES:
- dir::../src/A58_ACE.sv
- dir::../src/con32_one_instruction.v
- dir::../src/acti.v
- dir::../src/con32bits_parall.v
- dir::../src/four_palabras_uart.v
- dir::../src/mult_16b_bf.v
- dir::../src/punt_mo_seg.v
- dir::../src/salida.v
- dir::../src/suma_16b.v
- dir::../src/uart_tx_4in4.v
- dir::../src/uart_ultimo.v
# Enable plugin for better SystemVerilog support
# USE_SLANG: True
# SLANG_ARGUMENTS: ['--keep-hierarchy']

# Slightly smaller file sizes
PRIMARY_GDSII_STREAMOUT_TOOL: klayout
# Power / ground nets
VDD_NETS:
- VDD
GND_NETS:
- VSS


FP_SIZING: "absolute"
DIE_AREA: [0, 0, 1675, 1675]
CORE_AREA: [100, 100, 1575, 1575]
FP_DEF_TEMPLATE: "dir::../project_defs/ACE/A58_ACE.def"



# We need to add gf180mcu_fd_io__bi_24t
# due to the unused Y output for output only pads
IGNORE_DISCONNECTED_MODULES:
- gf180mcu_fd_io__bi_24t
- gf180mcu_ws_ip__id
- gf180mcu_ws_ip__logo

# Clock
CLOCK_PORT: clk_ref
CLOCK_NET: clk_ref
CLOCK_PERIOD: 50 # 50 MHz


ROUTING_CORES: 12              # Hilos para el Ruteador Detallado (TritonRoute)
KLAYOUT_DRC_THREADS: 12
KLAYOUT_DENSITY_THREADS: 12
KLAYOUT_XOR_THREADS: 12
DRT_THREADS: 12
STA_THREADS: 12

PNR_CORNERS:
  - "nom_ss_125C_4v50"
  - "nom_ff_n40C_5v50"
  - "nom_tt_025C_5v00"
  - "min_tt_025C_5v00"
  - "min_ff_n40C_5v50"
  - "min_ss_125C_4v50"
  - "max_tt_025C_5v00"
  - "max_ss_125C_4v50"
  - "max_ff_n40C_5v50"



DEDUPLICATE_CORNERS: true




RUN_POST_CTS_RESIZER_TIMING: true

RUN_POST_GRT_DESIGN_REPAIR: true
RUN_POST_GRT_RESIZER_TIMING: true
RUN_POST_GPL_DESIGN_REPAIR: true
RUN_POST_CTS_RESIZER_TIMING: true
GRT_ADJUSTMENT: 0.15
PL_RESIZER_HOLD_MAX_BUFFER_PCT: 35

PL_RESIZER_SETUP_MAX_BUFFER_PCT: 35

GRT_RESIZER_HOLD_MAX_BUFFER_PCT: 35
GRT_RESIZER_SETUP_MAX_BUFFER_PCT: 35
#15 # para ambos caso c7ando era area 3


PL_RESIZER_SETUP_GATE_CLONING: true
GRT_RESIZER_SETUP_GATE_CLONING: true

DESIGN_REPAIR_BUFFER_INPUT_PORTS: true
DESIGN_REPAIR_BUFFER_OUTPUT_PORTS: true
SYNTH_BUFFERING: true
SYNTH_SIZING: true
#  SYNTH_ABC_DFF: true                   # Optimiza registros redundantes
SYNTH_DIRECT_WIRE_BUFFERING: true


# Fix hold violations
PL_RESIZER_SETUP_SLACK_MARGIN: 4.0
#0.15
PL_RESIZER_HOLD_SLACK_MARGIN: 0.1
GRT_RESIZER_HOLD_SLACK_MARGIN: 0.025
GRT_RESIZER_SETUP_SLACK_MARGIN: 2.0
MAX_TRANSITION_CONSTRAINT: 2.5

PL_RESIZER_SETUP_REPAIR_TNS_PCT: 100
GRT_RESIZER_SETUP_REPAIR_TNS_PCT: 100
PL_RESIZER_HOLD_REPAIR_TNS_PCT: 100
GRT_RESIZER_HOLD_REPAIR_TNS_PCT: 100

DESIGN_REPAIR_MAX_WIRE_LENGTH: 500


########################################################
# Reparación agresiva de Slew y Cap en Placement y Routing
DESIGN_REPAIR_MAX_SLEW_PCT: 20
GRT_DESIGN_REPAIR_MAX_SLEW_PCT: 20
DESIGN_REPAIR_MAX_CAP_PCT: 20
GRT_DESIGN_REPAIR_MAX_CAP_PCT: 20

###########################################################

MAX_CAPACITANCE_CONSTRAINT: 0.2



# Prioridad de reparación:

PL_RESIZER_ALLOW_SETUP_VIOS: false

# Increase for more logic
# on your die
#PL_TARGET_DENSITY_PCT: 35
GRT_ALLOW_CONGESTION: false

MAX_FANOUT_CONSTRAINT: 24



CTS_CLK_BUFFERS:
- gf180mcu_fd_sc_mcu7t5v0__clkinv_2
- gf180mcu_fd_sc_mcu7t5v0__clkinv_4
- gf180mcu_fd_sc_mcu7t5v0__clkinv_8

#- gf180mcu_fd_sc_mcu7t5v0__clkbuf_2

#- gf180mcu_fd_sc_mcu7t5v0__clkbuf_4

#- gf180mcu_fd_sc_mcu7t5v0__clkbuf_8


CTS_ROOT_BUFFER: gf180mcu_fd_sc_mcu7t5v0__clkinv_16

# Fix antenna violations after DRT
#DRT_ANTENNA_REPAIR_ITERS: 10
#DRT_ANTENNA_REPAIR_MARGIN: 10 # %
RUN_ANTENNA_REPAIR: true

RUN_HEURISTIC_DIODE_INSERTION: false


GPL_CELL_PADDING: 1

DPL_CELL_PADDING: 1


# Routing / ESD.
RT_MIN_LAYER: Metal2
RT_MAX_LAYER: Metal5 #originalmente estaba en 4 y en false el pdn multilayer
SIGNAL_WIRE_RC_LAYERS: [Metal2, Metal3, Metal4]
# El reloj viaja en las capas más altas y limpias
CLOCK_WIRE_RC_LAYERS: [Metal3, Metal4]
RT_CLOCK_MIN_LAYER: Metal3
RT_CLOCK_MAX_LAYER: Metal4
# Bloquea al 100% el uso de Metal1 para ruteo intercelda
GRT_LAYER_ADJUSTMENTS: [1.0, 0.1, 0.0, 0.0, 0.0]


# PDN - Straps
PDN_MULTILAYER: true
FP_PDN_ENABLE_RAILS: true
FP_PDN_CHECK_NODES: true
#FP_PDN_VERTICAL_LAYER: Metal4
#FP_PDN_HORIZONTAL_LAYER: Metal5

FP_PDN_CORE_RING: true
FP_PDN_CORE_RING_VWIDTH: 20       # Ancho de 20um para soportar alta corriente en los bordes
FP_PDN_CORE_RING_HWIDTH: 20
FP_PDN_CORE_RING_VSPACING: 4.8      # Separación entre VDD y VSS
FP_PDN_CORE_RING_HSPACING: 4.8
PDN_VWIDTH: 10

PDN_HWIDTH: 10


# PDN - Core ring
PDN_CORE_RING: True
PDN_CORE_RING_CONNECT_TO_PADS: True


CTS_SINK_CLUSTERING_ENABLE: true

CTS_APPLY_NDR: full


CTS_SINK_CLUSTERING_SIZE: 32
#90

#256

#CTS_SINK_CLUSTERING_MAX_DIAMETER: 20
#100

PL_RESIZER_GATE_CLONING: true
CTS_OBSTRUCTION_AWARE: true             # Ayuda a esquivar las tiras de la PDN
CTS_BALANCE_LEVELS: true
#CTS_DISABLE_POST_PROCESSING: false      # Deja activo el post-procesamiento para sinks aislados
PL_OPTIMIZE_MIRRORING: true             # Voltea celdas para optimizar distancias de pines
CTS_SINK_BUFFER_MAX_CAP_DERATE_PCT: 100 # Sin derate artificial; usa el 100% de la capacidad de la celda
CTS_DELAY_BUFFER_DERATE_PCT: 100
#CTS_DISTANCE_BETWEEN_BUFFERS: 70
#CTS_CLK_MAX_WIRE_LENGTH: 300
#CTS_SINK_CLUSTERING_MAX_DIAMETER: 70
STA_MAX_VIOLATOR_COUNT: 200

SYNTH_STRATEGY: "DELAY 4"
LAYERS_RC:
  "*":
    Metal2:
      res: 0.000385861
      cap: 0.000135357
    Metal3:
      res: 0.000206673
      cap: 0.000146141
    Metal4:
      res: 0.000168609
      cap: 0.000150688
    Metal5:
      res: 7.92778e-05
      cap: 0.000155595

VIAS_R:
  "*":
    Via1:
      res: 4.23
    Via2:
      res: 4.23
    Via3:
      res: 4.23
    Via4:
      res: 4.23
  "max_*":
    Via1:
      res: 16.845
    Via2:
      res: 16.845
    Via3:
      res: 16.845
    Via4:
      res: 16.845

# Due to OpenROAD bug
# https://github.com/The-OpenROAD-Project/OpenROAD/issues/8229
#PL_TIME_DRIVEN: False
#PL_ROUTABILITY_DRIVEN: False

# Do not error on magic DRC violations
# Note: Passing magic DRC is not required for the submission.
# However, it is recommended to fix or carefully review all violations.
ERROR_ON_MAGIC_DRC: False

# Prevent false positive DRC errors in I/O cells
MAGIC_GDS_FLATGLOB:
# For contacts
- "*_CDNS_*"
# Foundry provided SRAMs
- "*$$*"
- "M1_N*"
- "M1_P*"
- "M2_M1*"
- "M3_M2*"
- "nmos_5p0*"
- "nmos_1p2*"
- "pmos_5p0*"
- "pmos_1p2*"
- "via1_*"
- "ypass_gate*"
- "G_ring_*"
# These additional cells must be flattened to get rid of 3.3V devices
# (DUALGATE drawn into high-level cells)
- "dcap_103*"
- "din_*"
- "mux821_*"
- "rdummy_*"
- "pmoscap_*"
- "xdec_*"
- "ypredec*"
- "xpredec*"
- "prexdec_*"
- "xdec8_*"
- "xdec16_*"
- "xdec32_*"
- "sa_*"

# Since we cannot meet the minimum density limit on Metal2,
# ignore active metal on previous and subsequent layers
# (DM.5_DM.7 and DM.4_DM.6). Dummy metal is moved to active
# metal during the precheck.
KLAYOUT_FILLER_OPTIONS:
  Metal2_ignore_active: true

# Because we have multiple power pads for one power domain
MAGIC_EXT_UNIQUE: notopports


#STA_MACRO_PRIORITIZE_NL: true

#MACROS:
#  con32_one_instruction:
#    gds:
#      - dir::build/con32_one_instruction/gds/con32_one_instruction.gds
#    lef:
#      - dir::build/con32_one_instruction/lef/con32_one_instruction.lef
#    vh:
#      - dir::build/con32_one_instruction/vh/con32_one_instruction.vh
#    nl:
#      - dir::build/con32_one_instruction/nl/con32_one_instruction.nl.v
#    pnl:
#      - dir::build/con32_one_instruction/pnl/con32_one_instruction.pnl.v
#    spice:
#      - dir::build/con32_one_instruction/spice/con32_one_instruction.spice
#    lib:
#      nom_tt_025C_5v00:
#      - dir::build/con32_one_instruction/lib/nom_tt_025C_5v00/con32_one_instruction__nom_tt_025C_5v00.lib
#      nom_ss_125C_4v50:
#      - dir::build/con32_one_instruction/lib/nom_ss_125C_4v50/con32_one_instruction__nom_ss_125C_4v50.lib
#      nom_ff_n40C_5v50:
#      - dir::build/con32_one_instruction/lib/nom_ff_n40C_5v50/con32_one_instruction__nom_ff_n40C_5v50.lib
#      min_tt_025C_5v00:
#      - dir::build/con32_one_instruction/lib/min_tt_025C_5v00/con32_one_instruction__min_tt_025C_5v00.lib
#      min_ss_125C_4v50:
#      - dir::build/con32_one_instruction/lib/min_ss_125C_4v50/con32_one_instruction__min_ss_125C_4v50.lib
#      min_ff_n40C_5v50:
#      - dir::build/con32_one_instruction/lib/min_ff_n40C_5v50/con32_one_instruction__min_ff_n40C_5v50.lib
#      max_tt_025C_5v00:
#      - dir::build/con32_one_instruction/lib/max_tt_025C_5v00/con32_one_instruction__max_tt_025C_5v00.lib
#      max_ss_125C_4v50:
#      - dir::build/con32_one_instruction/lib/max_ss_125C_4v50/con32_one_instruction__max_ss_125C_4v50.lib
#      max_ff_n40C_5v50:
#      - dir::build/con32_one_instruction/lib/max_ff_n40C_5v50/con32_one_instruction__max_ff_n40C_5v50.lib
#    spef:
#      min:
#      - dir::build/con32_one_instruction/spef/min/con32_one_instruction.min.spef
#      nom:
#      - dir::build/con32_one_instruction/spef/nom/con32_one_instruction.nom.spef
#      max:
#      - dir::build/con32_one_instruction/spef/max/con32_one_instruction.max.spef
#    instances:
      # Ajusta el nombre de la instancia según esté declarada en chip_core.sv
      # y sus coordenadas [X, Y] dentro del área útil del core
#      con32_one_instruction_u:
#        location: [120, 120]
#        orientation: N

# Conexión de alimentación para el macro

#PDN_MACRO_CONNECTIONS:
#- con32_one_instruction_u VDD VSS VDD VSS
# Halo size around macros while cutting rows.
# Workaround for: https://github.com/The-OpenROAD-Project/OpenROAD/issues/8868
#FP_MACRO_HORIZONTAL_HALO: 10
#FP_MACRO_VERTICAL_HALO: 10
#PDN_HORIZONTAL_HALO: 5
#PDN_VERTICAL_HALO: 5

PDN_CFG: dir::pdn_cfg.tcl
