###############################################################################
# Created by write_sdc
###############################################################################
current_design chip_top
###############################################################################
# Timing Constraints
###############################################################################
create_clock -name clk_PAD -period 50.0000 [get_pins {clk_pad/Y}]
set_clock_transition 0.1500 [get_clocks {clk_PAD}]
set_clock_uncertainty 0.2500 clk_PAD
set_propagated_clock [get_clocks {clk_PAD}]
set_input_delay 0.0000 -clock [get_clocks {clk_PAD}] -min -add_delay [get_ports {bidir_PAD[0]}]
set_input_delay 10.0000 -clock [get_clocks {clk_PAD}] -max -add_delay [get_ports {bidir_PAD[0]}]
set_input_delay 0.0000 -clock [get_clocks {clk_PAD}] -min -add_delay [get_ports {bidir_PAD[10]}]
set_input_delay 10.0000 -clock [get_clocks {clk_PAD}] -max -add_delay [get_ports {bidir_PAD[10]}]
set_input_delay 0.0000 -clock [get_clocks {clk_PAD}] -min -add_delay [get_ports {bidir_PAD[11]}]
set_input_delay 10.0000 -clock [get_clocks {clk_PAD}] -max -add_delay [get_ports {bidir_PAD[11]}]
set_input_delay 0.0000 -clock [get_clocks {clk_PAD}] -min -add_delay [get_ports {bidir_PAD[12]}]
set_input_delay 10.0000 -clock [get_clocks {clk_PAD}] -max -add_delay [get_ports {bidir_PAD[12]}]
set_input_delay 0.0000 -clock [get_clocks {clk_PAD}] -min -add_delay [get_ports {bidir_PAD[13]}]
set_input_delay 10.0000 -clock [get_clocks {clk_PAD}] -max -add_delay [get_ports {bidir_PAD[13]}]
set_input_delay 0.0000 -clock [get_clocks {clk_PAD}] -min -add_delay [get_ports {bidir_PAD[14]}]
set_input_delay 10.0000 -clock [get_clocks {clk_PAD}] -max -add_delay [get_ports {bidir_PAD[14]}]
set_input_delay 0.0000 -clock [get_clocks {clk_PAD}] -min -add_delay [get_ports {bidir_PAD[15]}]
set_input_delay 10.0000 -clock [get_clocks {clk_PAD}] -max -add_delay [get_ports {bidir_PAD[15]}]
set_input_delay 0.0000 -clock [get_clocks {clk_PAD}] -min -add_delay [get_ports {bidir_PAD[16]}]
set_input_delay 10.0000 -clock [get_clocks {clk_PAD}] -max -add_delay [get_ports {bidir_PAD[16]}]
set_input_delay 0.0000 -clock [get_clocks {clk_PAD}] -min -add_delay [get_ports {bidir_PAD[17]}]
set_input_delay 10.0000 -clock [get_clocks {clk_PAD}] -max -add_delay [get_ports {bidir_PAD[17]}]
set_input_delay 0.0000 -clock [get_clocks {clk_PAD}] -min -add_delay [get_ports {bidir_PAD[18]}]
set_input_delay 10.0000 -clock [get_clocks {clk_PAD}] -max -add_delay [get_ports {bidir_PAD[18]}]
set_input_delay 0.0000 -clock [get_clocks {clk_PAD}] -min -add_delay [get_ports {bidir_PAD[19]}]
set_input_delay 10.0000 -clock [get_clocks {clk_PAD}] -max -add_delay [get_ports {bidir_PAD[19]}]
set_input_delay 0.0000 -clock [get_clocks {clk_PAD}] -min -add_delay [get_ports {bidir_PAD[1]}]
set_input_delay 10.0000 -clock [get_clocks {clk_PAD}] -max -add_delay [get_ports {bidir_PAD[1]}]
set_input_delay 0.0000 -clock [get_clocks {clk_PAD}] -min -add_delay [get_ports {bidir_PAD[20]}]
set_input_delay 10.0000 -clock [get_clocks {clk_PAD}] -max -add_delay [get_ports {bidir_PAD[20]}]
set_input_delay 0.0000 -clock [get_clocks {clk_PAD}] -min -add_delay [get_ports {bidir_PAD[21]}]
set_input_delay 10.0000 -clock [get_clocks {clk_PAD}] -max -add_delay [get_ports {bidir_PAD[21]}]
set_input_delay 0.0000 -clock [get_clocks {clk_PAD}] -min -add_delay [get_ports {bidir_PAD[22]}]
set_input_delay 10.0000 -clock [get_clocks {clk_PAD}] -max -add_delay [get_ports {bidir_PAD[22]}]
set_input_delay 0.0000 -clock [get_clocks {clk_PAD}] -min -add_delay [get_ports {bidir_PAD[23]}]
set_input_delay 10.0000 -clock [get_clocks {clk_PAD}] -max -add_delay [get_ports {bidir_PAD[23]}]
set_input_delay 0.0000 -clock [get_clocks {clk_PAD}] -min -add_delay [get_ports {bidir_PAD[24]}]
set_input_delay 10.0000 -clock [get_clocks {clk_PAD}] -max -add_delay [get_ports {bidir_PAD[24]}]
set_input_delay 0.0000 -clock [get_clocks {clk_PAD}] -min -add_delay [get_ports {bidir_PAD[25]}]
set_input_delay 10.0000 -clock [get_clocks {clk_PAD}] -max -add_delay [get_ports {bidir_PAD[25]}]
set_input_delay 0.0000 -clock [get_clocks {clk_PAD}] -min -add_delay [get_ports {bidir_PAD[26]}]
set_input_delay 10.0000 -clock [get_clocks {clk_PAD}] -max -add_delay [get_ports {bidir_PAD[26]}]
set_input_delay 0.0000 -clock [get_clocks {clk_PAD}] -min -add_delay [get_ports {bidir_PAD[27]}]
set_input_delay 10.0000 -clock [get_clocks {clk_PAD}] -max -add_delay [get_ports {bidir_PAD[27]}]
set_input_delay 0.0000 -clock [get_clocks {clk_PAD}] -min -add_delay [get_ports {bidir_PAD[28]}]
set_input_delay 10.0000 -clock [get_clocks {clk_PAD}] -max -add_delay [get_ports {bidir_PAD[28]}]
set_input_delay 0.0000 -clock [get_clocks {clk_PAD}] -min -add_delay [get_ports {bidir_PAD[29]}]
set_input_delay 10.0000 -clock [get_clocks {clk_PAD}] -max -add_delay [get_ports {bidir_PAD[29]}]
set_input_delay 0.0000 -clock [get_clocks {clk_PAD}] -min -add_delay [get_ports {bidir_PAD[2]}]
set_input_delay 10.0000 -clock [get_clocks {clk_PAD}] -max -add_delay [get_ports {bidir_PAD[2]}]
set_input_delay 0.0000 -clock [get_clocks {clk_PAD}] -min -add_delay [get_ports {bidir_PAD[30]}]
set_input_delay 10.0000 -clock [get_clocks {clk_PAD}] -max -add_delay [get_ports {bidir_PAD[30]}]
set_input_delay 0.0000 -clock [get_clocks {clk_PAD}] -min -add_delay [get_ports {bidir_PAD[31]}]
set_input_delay 10.0000 -clock [get_clocks {clk_PAD}] -max -add_delay [get_ports {bidir_PAD[31]}]
set_input_delay 0.0000 -clock [get_clocks {clk_PAD}] -min -add_delay [get_ports {bidir_PAD[32]}]
set_input_delay 10.0000 -clock [get_clocks {clk_PAD}] -max -add_delay [get_ports {bidir_PAD[32]}]
set_input_delay 0.0000 -clock [get_clocks {clk_PAD}] -min -add_delay [get_ports {bidir_PAD[33]}]
set_input_delay 10.0000 -clock [get_clocks {clk_PAD}] -max -add_delay [get_ports {bidir_PAD[33]}]
set_input_delay 0.0000 -clock [get_clocks {clk_PAD}] -min -add_delay [get_ports {bidir_PAD[34]}]
set_input_delay 10.0000 -clock [get_clocks {clk_PAD}] -max -add_delay [get_ports {bidir_PAD[34]}]
set_input_delay 0.0000 -clock [get_clocks {clk_PAD}] -min -add_delay [get_ports {bidir_PAD[35]}]
set_input_delay 10.0000 -clock [get_clocks {clk_PAD}] -max -add_delay [get_ports {bidir_PAD[35]}]
set_input_delay 0.0000 -clock [get_clocks {clk_PAD}] -min -add_delay [get_ports {bidir_PAD[36]}]
set_input_delay 10.0000 -clock [get_clocks {clk_PAD}] -max -add_delay [get_ports {bidir_PAD[36]}]
set_input_delay 0.0000 -clock [get_clocks {clk_PAD}] -min -add_delay [get_ports {bidir_PAD[37]}]
set_input_delay 10.0000 -clock [get_clocks {clk_PAD}] -max -add_delay [get_ports {bidir_PAD[37]}]
set_input_delay 0.0000 -clock [get_clocks {clk_PAD}] -min -add_delay [get_ports {bidir_PAD[38]}]
set_input_delay 10.0000 -clock [get_clocks {clk_PAD}] -max -add_delay [get_ports {bidir_PAD[38]}]
set_input_delay 0.0000 -clock [get_clocks {clk_PAD}] -min -add_delay [get_ports {bidir_PAD[39]}]
set_input_delay 10.0000 -clock [get_clocks {clk_PAD}] -max -add_delay [get_ports {bidir_PAD[39]}]
set_input_delay 0.0000 -clock [get_clocks {clk_PAD}] -min -add_delay [get_ports {bidir_PAD[3]}]
set_input_delay 10.0000 -clock [get_clocks {clk_PAD}] -max -add_delay [get_ports {bidir_PAD[3]}]
set_input_delay 0.0000 -clock [get_clocks {clk_PAD}] -min -add_delay [get_ports {bidir_PAD[4]}]
set_input_delay 10.0000 -clock [get_clocks {clk_PAD}] -max -add_delay [get_ports {bidir_PAD[4]}]
set_input_delay 0.0000 -clock [get_clocks {clk_PAD}] -min -add_delay [get_ports {bidir_PAD[5]}]
set_input_delay 10.0000 -clock [get_clocks {clk_PAD}] -max -add_delay [get_ports {bidir_PAD[5]}]
set_input_delay 0.0000 -clock [get_clocks {clk_PAD}] -min -add_delay [get_ports {bidir_PAD[6]}]
set_input_delay 10.0000 -clock [get_clocks {clk_PAD}] -max -add_delay [get_ports {bidir_PAD[6]}]
set_input_delay 0.0000 -clock [get_clocks {clk_PAD}] -min -add_delay [get_ports {bidir_PAD[7]}]
set_input_delay 10.0000 -clock [get_clocks {clk_PAD}] -max -add_delay [get_ports {bidir_PAD[7]}]
set_input_delay 0.0000 -clock [get_clocks {clk_PAD}] -min -add_delay [get_ports {bidir_PAD[8]}]
set_input_delay 10.0000 -clock [get_clocks {clk_PAD}] -max -add_delay [get_ports {bidir_PAD[8]}]
set_input_delay 0.0000 -clock [get_clocks {clk_PAD}] -min -add_delay [get_ports {bidir_PAD[9]}]
set_input_delay 10.0000 -clock [get_clocks {clk_PAD}] -max -add_delay [get_ports {bidir_PAD[9]}]
set_input_delay 0.0000 -clock [get_clocks {clk_PAD}] -min -add_delay [get_ports {input_PAD[0]}]
set_input_delay 10.0000 -clock [get_clocks {clk_PAD}] -max -add_delay [get_ports {input_PAD[0]}]
set_input_delay 0.0000 -clock [get_clocks {clk_PAD}] -min -add_delay [get_ports {input_PAD[10]}]
set_input_delay 10.0000 -clock [get_clocks {clk_PAD}] -max -add_delay [get_ports {input_PAD[10]}]
set_input_delay 0.0000 -clock [get_clocks {clk_PAD}] -min -add_delay [get_ports {input_PAD[11]}]
set_input_delay 10.0000 -clock [get_clocks {clk_PAD}] -max -add_delay [get_ports {input_PAD[11]}]
set_input_delay 0.0000 -clock [get_clocks {clk_PAD}] -min -add_delay [get_ports {input_PAD[1]}]
set_input_delay 10.0000 -clock [get_clocks {clk_PAD}] -max -add_delay [get_ports {input_PAD[1]}]
set_input_delay 0.0000 -clock [get_clocks {clk_PAD}] -min -add_delay [get_ports {input_PAD[2]}]
set_input_delay 10.0000 -clock [get_clocks {clk_PAD}] -max -add_delay [get_ports {input_PAD[2]}]
set_input_delay 0.0000 -clock [get_clocks {clk_PAD}] -min -add_delay [get_ports {input_PAD[3]}]
set_input_delay 10.0000 -clock [get_clocks {clk_PAD}] -max -add_delay [get_ports {input_PAD[3]}]
set_input_delay 0.0000 -clock [get_clocks {clk_PAD}] -min -add_delay [get_ports {input_PAD[4]}]
set_input_delay 10.0000 -clock [get_clocks {clk_PAD}] -max -add_delay [get_ports {input_PAD[4]}]
set_input_delay 0.0000 -clock [get_clocks {clk_PAD}] -min -add_delay [get_ports {input_PAD[5]}]
set_input_delay 10.0000 -clock [get_clocks {clk_PAD}] -max -add_delay [get_ports {input_PAD[5]}]
set_input_delay 0.0000 -clock [get_clocks {clk_PAD}] -min -add_delay [get_ports {input_PAD[6]}]
set_input_delay 10.0000 -clock [get_clocks {clk_PAD}] -max -add_delay [get_ports {input_PAD[6]}]
set_input_delay 0.0000 -clock [get_clocks {clk_PAD}] -min -add_delay [get_ports {input_PAD[7]}]
set_input_delay 10.0000 -clock [get_clocks {clk_PAD}] -max -add_delay [get_ports {input_PAD[7]}]
set_input_delay 0.0000 -clock [get_clocks {clk_PAD}] -min -add_delay [get_ports {input_PAD[8]}]
set_input_delay 10.0000 -clock [get_clocks {clk_PAD}] -max -add_delay [get_ports {input_PAD[8]}]
set_input_delay 0.0000 -clock [get_clocks {clk_PAD}] -min -add_delay [get_ports {input_PAD[9]}]
set_input_delay 10.0000 -clock [get_clocks {clk_PAD}] -max -add_delay [get_ports {input_PAD[9]}]
set_input_delay 0.0000 -clock [get_clocks {clk_PAD}] -min -add_delay [get_ports {rst_n_PAD}]
set_input_delay 2.0000 -clock [get_clocks {clk_PAD}] -max -add_delay [get_ports {rst_n_PAD}]
set_output_delay 10.0000 -clock [get_clocks {clk_PAD}] -add_delay [get_ports {bidir_PAD[0]}]
set_output_delay 10.0000 -clock [get_clocks {clk_PAD}] -add_delay [get_ports {bidir_PAD[10]}]
set_output_delay 10.0000 -clock [get_clocks {clk_PAD}] -add_delay [get_ports {bidir_PAD[11]}]
set_output_delay 10.0000 -clock [get_clocks {clk_PAD}] -add_delay [get_ports {bidir_PAD[12]}]
set_output_delay 10.0000 -clock [get_clocks {clk_PAD}] -add_delay [get_ports {bidir_PAD[13]}]
set_output_delay 10.0000 -clock [get_clocks {clk_PAD}] -add_delay [get_ports {bidir_PAD[14]}]
set_output_delay 10.0000 -clock [get_clocks {clk_PAD}] -add_delay [get_ports {bidir_PAD[15]}]
set_output_delay 10.0000 -clock [get_clocks {clk_PAD}] -add_delay [get_ports {bidir_PAD[16]}]
set_output_delay 10.0000 -clock [get_clocks {clk_PAD}] -add_delay [get_ports {bidir_PAD[17]}]
set_output_delay 10.0000 -clock [get_clocks {clk_PAD}] -add_delay [get_ports {bidir_PAD[18]}]
set_output_delay 10.0000 -clock [get_clocks {clk_PAD}] -add_delay [get_ports {bidir_PAD[19]}]
set_output_delay 10.0000 -clock [get_clocks {clk_PAD}] -add_delay [get_ports {bidir_PAD[1]}]
set_output_delay 10.0000 -clock [get_clocks {clk_PAD}] -add_delay [get_ports {bidir_PAD[20]}]
set_output_delay 10.0000 -clock [get_clocks {clk_PAD}] -add_delay [get_ports {bidir_PAD[21]}]
set_output_delay 10.0000 -clock [get_clocks {clk_PAD}] -add_delay [get_ports {bidir_PAD[22]}]
set_output_delay 10.0000 -clock [get_clocks {clk_PAD}] -add_delay [get_ports {bidir_PAD[23]}]
set_output_delay 10.0000 -clock [get_clocks {clk_PAD}] -add_delay [get_ports {bidir_PAD[24]}]
set_output_delay 10.0000 -clock [get_clocks {clk_PAD}] -add_delay [get_ports {bidir_PAD[25]}]
set_output_delay 10.0000 -clock [get_clocks {clk_PAD}] -add_delay [get_ports {bidir_PAD[26]}]
set_output_delay 10.0000 -clock [get_clocks {clk_PAD}] -add_delay [get_ports {bidir_PAD[27]}]
set_output_delay 10.0000 -clock [get_clocks {clk_PAD}] -add_delay [get_ports {bidir_PAD[28]}]
set_output_delay 10.0000 -clock [get_clocks {clk_PAD}] -add_delay [get_ports {bidir_PAD[29]}]
set_output_delay 10.0000 -clock [get_clocks {clk_PAD}] -add_delay [get_ports {bidir_PAD[2]}]
set_output_delay 10.0000 -clock [get_clocks {clk_PAD}] -add_delay [get_ports {bidir_PAD[30]}]
set_output_delay 10.0000 -clock [get_clocks {clk_PAD}] -add_delay [get_ports {bidir_PAD[31]}]
set_output_delay 10.0000 -clock [get_clocks {clk_PAD}] -add_delay [get_ports {bidir_PAD[32]}]
set_output_delay 10.0000 -clock [get_clocks {clk_PAD}] -add_delay [get_ports {bidir_PAD[33]}]
set_output_delay 10.0000 -clock [get_clocks {clk_PAD}] -add_delay [get_ports {bidir_PAD[34]}]
set_output_delay 10.0000 -clock [get_clocks {clk_PAD}] -add_delay [get_ports {bidir_PAD[35]}]
set_output_delay 10.0000 -clock [get_clocks {clk_PAD}] -add_delay [get_ports {bidir_PAD[36]}]
set_output_delay 10.0000 -clock [get_clocks {clk_PAD}] -add_delay [get_ports {bidir_PAD[37]}]
set_output_delay 10.0000 -clock [get_clocks {clk_PAD}] -add_delay [get_ports {bidir_PAD[38]}]
set_output_delay 10.0000 -clock [get_clocks {clk_PAD}] -add_delay [get_ports {bidir_PAD[39]}]
set_output_delay 10.0000 -clock [get_clocks {clk_PAD}] -add_delay [get_ports {bidir_PAD[3]}]
set_output_delay 10.0000 -clock [get_clocks {clk_PAD}] -add_delay [get_ports {bidir_PAD[4]}]
set_output_delay 10.0000 -clock [get_clocks {clk_PAD}] -add_delay [get_ports {bidir_PAD[5]}]
set_output_delay 10.0000 -clock [get_clocks {clk_PAD}] -add_delay [get_ports {bidir_PAD[6]}]
set_output_delay 10.0000 -clock [get_clocks {clk_PAD}] -add_delay [get_ports {bidir_PAD[7]}]
set_output_delay 10.0000 -clock [get_clocks {clk_PAD}] -add_delay [get_ports {bidir_PAD[8]}]
set_output_delay 10.0000 -clock [get_clocks {clk_PAD}] -add_delay [get_ports {bidir_PAD[9]}]
###############################################################################
# Environment
###############################################################################
set_load -pin_load 0.0729 [get_ports {clk_PAD}]
set_load -pin_load 0.0729 [get_ports {rst_n_PAD}]
set_load -pin_load 0.0729 [get_ports {analog_PAD[1]}]
set_load -pin_load 0.0729 [get_ports {analog_PAD[0]}]
set_load -pin_load 0.0729 [get_ports {bidir_PAD[39]}]
set_load -pin_load 0.0729 [get_ports {bidir_PAD[38]}]
set_load -pin_load 0.0729 [get_ports {bidir_PAD[37]}]
set_load -pin_load 0.0729 [get_ports {bidir_PAD[36]}]
set_load -pin_load 0.0729 [get_ports {bidir_PAD[35]}]
set_load -pin_load 0.0729 [get_ports {bidir_PAD[34]}]
set_load -pin_load 0.0729 [get_ports {bidir_PAD[33]}]
set_load -pin_load 0.0729 [get_ports {bidir_PAD[32]}]
set_load -pin_load 0.0729 [get_ports {bidir_PAD[31]}]
set_load -pin_load 0.0729 [get_ports {bidir_PAD[30]}]
set_load -pin_load 0.0729 [get_ports {bidir_PAD[29]}]
set_load -pin_load 0.0729 [get_ports {bidir_PAD[28]}]
set_load -pin_load 0.0729 [get_ports {bidir_PAD[27]}]
set_load -pin_load 0.0729 [get_ports {bidir_PAD[26]}]
set_load -pin_load 0.0729 [get_ports {bidir_PAD[25]}]
set_load -pin_load 0.0729 [get_ports {bidir_PAD[24]}]
set_load -pin_load 0.0729 [get_ports {bidir_PAD[23]}]
set_load -pin_load 0.0729 [get_ports {bidir_PAD[22]}]
set_load -pin_load 0.0729 [get_ports {bidir_PAD[21]}]
set_load -pin_load 0.0729 [get_ports {bidir_PAD[20]}]
set_load -pin_load 0.0729 [get_ports {bidir_PAD[19]}]
set_load -pin_load 0.0729 [get_ports {bidir_PAD[18]}]
set_load -pin_load 0.0729 [get_ports {bidir_PAD[17]}]
set_load -pin_load 0.0729 [get_ports {bidir_PAD[16]}]
set_load -pin_load 0.0729 [get_ports {bidir_PAD[15]}]
set_load -pin_load 0.0729 [get_ports {bidir_PAD[14]}]
set_load -pin_load 0.0729 [get_ports {bidir_PAD[13]}]
set_load -pin_load 0.0729 [get_ports {bidir_PAD[12]}]
set_load -pin_load 0.0729 [get_ports {bidir_PAD[11]}]
set_load -pin_load 0.0729 [get_ports {bidir_PAD[10]}]
set_load -pin_load 0.0729 [get_ports {bidir_PAD[9]}]
set_load -pin_load 0.0729 [get_ports {bidir_PAD[8]}]
set_load -pin_load 0.0729 [get_ports {bidir_PAD[7]}]
set_load -pin_load 0.0729 [get_ports {bidir_PAD[6]}]
set_load -pin_load 0.0729 [get_ports {bidir_PAD[5]}]
set_load -pin_load 0.0729 [get_ports {bidir_PAD[4]}]
set_load -pin_load 0.0729 [get_ports {bidir_PAD[3]}]
set_load -pin_load 0.0729 [get_ports {bidir_PAD[2]}]
set_load -pin_load 0.0729 [get_ports {bidir_PAD[1]}]
set_load -pin_load 0.0729 [get_ports {bidir_PAD[0]}]
set_load -pin_load 0.0729 [get_ports {input_PAD[11]}]
set_load -pin_load 0.0729 [get_ports {input_PAD[10]}]
set_load -pin_load 0.0729 [get_ports {input_PAD[9]}]
set_load -pin_load 0.0729 [get_ports {input_PAD[8]}]
set_load -pin_load 0.0729 [get_ports {input_PAD[7]}]
set_load -pin_load 0.0729 [get_ports {input_PAD[6]}]
set_load -pin_load 0.0729 [get_ports {input_PAD[5]}]
set_load -pin_load 0.0729 [get_ports {input_PAD[4]}]
set_load -pin_load 0.0729 [get_ports {input_PAD[3]}]
set_load -pin_load 0.0729 [get_ports {input_PAD[2]}]
set_load -pin_load 0.0729 [get_ports {input_PAD[1]}]
set_load -pin_load 0.0729 [get_ports {input_PAD[0]}]
set_input_transition 0.5000 [get_ports {rst_n_PAD}]
###############################################################################
# Design Rules
###############################################################################
set_max_transition 3.0000 [current_design]
set_max_capacitance 0.2000 [current_design]
set_max_fanout 10.0000 [current_design]
